export enum PUBLIC_ROUTE {
  UNKNOWN = "#",
  HOME = "/",
  LOGIN = "/login",
  REGISTRATION = "/register",
  NOT_FOUND = "*",
  FORGOT_PASSWORD = "/forgot-password",
  FEATURES = "/features",
  PRICING = "/pricing",
  TEMPLATES = "/templates",
  INTEGRATIONS = "/integrations",
  HELP = "/help",
  GUIDE = "/guides",
  API_DOC = "/api",
  COMMUNITY = "/community",
  ABOUT_US = "/about",
  CAREERS = "/careers",
  BLOB = "/blog",
  CONTACT_US = "/contact-us",
  COOKIES_POLICY = "/cookies",
  PRIVACY_POLICY = "/privacy",
  TERM_POLICY = "/terms",
  VERIFY_USER_EMAIL = "/verify-email",
}

export enum PRIVATE_ROUTE {
  DASHBOARD = "/dashboard",
  USER_PROFILE = "/profile",
  INVITATION = "invitation/:id/:userId",
  WORKSPACES = "/workspaces",
  WORKSPACE = "/workspace/:id",
  BOARDS = "/boards",
  BOARD = "/board/:id",
  BOARD_STATISTICS = "/board/:id/statistics",
  INVITATIONS = "invitations",
}
